
import React, { useState } from 'react';
import { Search, CreditCard, Shield, MessageCircle, ChevronDown, ChevronUp, Zap, Box } from 'lucide-react';

interface FaqItem {
  question: string;
  answer: string;
  category: string;
}

const FAQS: FaqItem[] = [
  {
    category: 'Access & Delivery',
    question: "How do I receive my prompts after purchase?",
    answer: "We do not send prompts via email. Instead, all your purchased content is instantly available in the 'My Library' section of your Dashboard. This ensures you always have access to the most up-to-date versions."
  },
  {
    category: 'Billing',
    question: "Where can I find my invoice?",
    answer: "Invoices are generated and available in your Dashboard under 'Order History' within 24 hours of your purchase. You can view and download them at any time."
  },
  {
    category: 'Technical',
    question: "What if the prompt doesn't work with the specified model?",
    answer: "Our prompts are battle-tested weekly. If an update to a model (like GPT-4) breaks functionality, we update the prompt in your Dashboard library. You get lifetime updates for every purchase."
  },
  {
    category: 'Technical',
    question: "Do I need a paid subscription for AI models?",
    answer: "Not necessarily. Our prompts are expertly engineered to work very well on the free tiers of the top AI models. However, a subscription always helps."
  },
  {
    category: 'Licensing',
    question: "Can I use the outputs for commercial projects?",
    answer: "Yes. You have full commercial rights to the outputs generated by our prompts. You may not, however, resell or redistribute the prompt logic itself."
  }
];

export const HelpCenter: React.FC = () => {
  const [searchQuery, setSearchQuery] = useState('');
  const [openFaqIndex, setOpenFaqIndex] = useState<number | null>(null);

  const toggleFaq = (index: number) => {
    setOpenFaqIndex(openFaqIndex === index ? null : index);
  };

  const filteredFaqs = FAQS.filter(faq => 
    faq.question.toLowerCase().includes(searchQuery.toLowerCase()) || 
    faq.answer.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="min-h-screen pb-20">
      {/* Hero Search Section */}
      <section className="relative px-4 py-20 text-center sm:px-6 lg:px-8 bg-secondary/30 border-b border-white/5 overflow-hidden">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[800px] h-[400px] bg-accent/5 blur-[100px] rounded-full pointer-events-none -z-10" />
        
        <h1 className="mx-auto max-w-2xl font-display text-4xl font-bold tracking-tight text-white mb-6">
            How can we assist you?
        </h1>
        
        <div className="mx-auto max-w-xl relative">
            <input 
                type="text" 
                placeholder="Search for answers (e.g., 'invoice', 'licensing')..." 
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full h-14 pl-12 pr-4 rounded-xl bg-primary border border-white/10 text-white placeholder-textSecondary focus:border-accent focus:ring-1 focus:ring-accent/50 outline-none transition-all shadow-xl"
            />
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-textSecondary" size={20} />
        </div>
      </section>

      <div className="mx-auto max-w-5xl px-4 py-12 sm:px-6 lg:px-8">
        
        {/* Support Categories */}
        {!searchQuery && (
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-16">
                {[
                    { icon: Box, title: 'Access & Delivery', desc: 'Where to find your prompts.' },
                    { icon: CreditCard, title: 'Billing & Subscriptions', desc: 'Invoices and refund policy.' },
                    { icon: Shield, title: 'Licensing', desc: 'Commercial rights and usage policies.' },
                ].map((item, idx) => (
                    <div key={idx} className="group p-6 rounded-2xl glass-card border border-white/5 hover:border-accent/30 transition-all hover:-translate-y-1 cursor-pointer">
                        <div className="h-10 w-10 rounded-lg bg-accent/10 flex items-center justify-center mb-4 group-hover:bg-accent text-accent group-hover:text-primary transition-colors">
                            <item.icon size={20} />
                        </div>
                        <h3 className="font-bold text-white mb-2">{item.title}</h3>
                        <p className="text-sm text-textSecondary">{item.desc}</p>
                    </div>
                ))}
            </div>
        )}

        {/* FAQ Accordion */}
        <div className="max-w-3xl mx-auto">
            <h2 className="text-2xl font-display font-bold text-white mb-8">
                {searchQuery ? 'Search Results' : 'Frequently Asked Questions'}
            </h2>
            
            <div className="space-y-4">
                {filteredFaqs.length > 0 ? (
                    filteredFaqs.map((faq, index) => (
                        <div 
                            key={index} 
                            className={`rounded-xl border transition-all duration-300 overflow-hidden ${
                                openFaqIndex === index 
                                ? 'bg-secondary/60 border-accent/30' 
                                : 'bg-secondary/20 border-white/5 hover:border-white/10'
                            }`}
                        >
                            <button 
                                onClick={() => toggleFaq(index)}
                                className="w-full flex items-center justify-between p-5 text-left"
                            >
                                <span className={`font-medium ${openFaqIndex === index ? 'text-white' : 'text-textPrimary'}`}>
                                    {faq.question}
                                </span>
                                {openFaqIndex === index ? (
                                    <ChevronUp className="text-accent" size={18} />
                                ) : (
                                    <ChevronDown className="text-textSecondary" size={18} />
                                )}
                            </button>
                            
                            <div 
                                className={`px-5 text-sm text-textSecondary leading-relaxed transition-all duration-300 ease-in-out ${
                                    openFaqIndex === index ? 'max-h-40 pb-5 opacity-100' : 'max-h-0 opacity-0'
                                }`}
                            >
                                {faq.answer}
                            </div>
                        </div>
                    ))
                ) : (
                    <div className="text-center py-10 text-textSecondary">
                        No results found for "{searchQuery}".
                    </div>
                )}
            </div>
        </div>

        {/* Still need help? */}
        <div className="mt-20 rounded-2xl bg-gradient-to-r from-accent/10 to-retro/10 border border-white/10 p-8 text-center backdrop-blur-sm">
             <div className="inline-flex items-center justify-center w-12 h-12 rounded-full bg-secondary mb-4 ring-1 ring-white/10">
                <MessageCircle size={24} className="text-white" />
             </div>
             <h3 className="text-xl font-bold text-white mb-2">Still need help?</h3>
             <p className="text-textSecondary mb-6 max-w-md mx-auto">Our engineering team is available Monday to Friday to assist with complex integration issues.</p>
             
             <div className="flex flex-col items-center gap-2">
                 <div className="bg-secondary/50 border border-white/10 px-6 py-3 rounded-lg text-accent font-mono font-bold text-lg select-all shadow-inner">
                    saisrikiran@yahoo.com
                 </div>
                 <p className="text-sm text-textSecondary mt-2">
                    Contact us through this email. Expect a response from our team within 24 hours.
                 </p>
             </div>
        </div>

      </div>
    </div>
  );
};
